# Makefile for calendar example
# Author: Hsiaoming Yang <lepture@me.com>
# Website: http://lepture.com


doc: index

index:
	doki.py -l js -t assets/layout.html --title=Calendar assets/index.md > index.html
